name: photoTaggerEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - django=2.1.2
  - numpy=1.15.2
  - pillow=5.3.0
  - python=3.6.6
  - tensorflow=1.11.0
  - coverage=4.5.1
  - pip:
    - django-crispy-forms==1.7.2
    - scout-apm
    - cloudinary
